#ifndef FC_FCIMU_IMUCONFIG_H_
#define FC_FCIMU_IMUCONFIG_H_

#define IMU_LIN_ACC_LPF_ENABLED 0
#define IMU_LIN_ACC_LPF_CUTOFF  50.0f

#define IMU_Z_ACC_DB  0.0f

#define IMU_ALT_VEL_BIAS_LEAK_FACTOR  0.55f

#define IMU_LIN_ACC_VALID_ANGLE  30.0f
#define IMU_ACC_VEL_GAIN  9.81f

#endif
