#ifndef FC_FCIMU_IMUCONFIG_H_
#define FC_FCIMU_IMUCONFIG_H_

#define IMU_LIN_ACC_LPF_ENABLED 0
#define IMU_LIN_ACC_LPF_CUTOFF  0.85f

#define IMU_X_ACC_DB  0.0f
#define IMU_Y_ACC_DB  0.0f
#define IMU_Z_ACC_DB  0.0f

#define IMU_ALT_VEL_BIAS_LEAK_FACTOR  0.65f
#define IMU_LIN_VEL_BIAS_LEAK_FACTOR  0.65f

#define IMU_LIN_ACC_VALID_ANGLE  10.0f
#define IMU_ACC_VEL_GAIN  9.8f

#endif
