#ifndef _MANAGERCONFIG_H_
#define _MANAGERCONFIG_H_

// Low Priority tasks
#define CONFIG_MANAGER_STACK_SIZE 1024 * 4
#define CONFIG_MANAGER_PRIORITY 5
#define CONFIG_MANAGER_CPU 1

#define DEBUGGER_STACK_SIZE 1024 * 4
#define DEBUGGER_PRIORITY 1
#define DEBUGGER_CPU 1

#define ALTITUDE_MANAGER_STACK_SIZE 1024 * 4
#define ALTITUDE_MANAGER_PRIORITY 9
#define ALTITUDE_MANAGER_CPU 1

// High Priority tasks
#define ATTITUDE_MANAGER_STACK_SIZE 1024 * 8
#define ATTITUDE_MANAGER_PRIORITY 9
#define ATTITUDE_MANAGER_CPU 0

#define RC_MANAGER_STACK_SIZE 1024 * 4
#define RC_MANAGER_PRIORITY 10
#define RC_MANAGER_CPU 0

#define RC_WIFI_MANAGER_STACK_SIZE 1024 * 6
#define RC_WIFI_MANAGER_PRIORITY 10
#define RC_WIFI_MANAGER_CPU 1

#define PWM_MANAGER_STACK_SIZE 1024 * 4
#define PWM_MANAGER_PRIORITY 8
#define PWM_MANAGER_CPU 0

#endif
